const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const root = path.resolve(__dirname, '..', '..', '..', '..')
const read = (relative) => fs.readFileSync(path.join(root, relative), 'utf8')

test('new course-build client uses the formal outline, script, proposal and unified upload APIs', () => {
  const source = read('frontend/src/api/course_build.js')
  const backend = read('backend/app/api/v1/endpoints/course_build.py')
  assert.match(source, /outlines\/drafts/)
  assert.match(source, /\/scripts\//)
  assert.match(source, /\/patch-proposals/)
  assert.match(source, /\/courses\/\$\{encodeURIComponent\(courseId\)\}\/materials/)
  assert.match(source, /initial-draft\/rebuild/)
  assert.match(backend, /@course_build_router\.post\(["']\/course\/\{course_id\}\/initial-draft\/rebuild["']\)/)
  assert.match(backend, /rebuild_unreviewed_initial_draft/)
  assert.match(source, /createCourseWorkspace/)
  assert.doesNotMatch(source, /createBuildMaterial|markBuildMaterialParse/)
})

test('new construction backend guards all teacher mutations with Course Access v1', () => {
  const source = read('backend/app/api/v1/endpoints/course_outline.py')
  assert.match(source, /@course_outline_router\.post\(["']\/course\/\{course_id\}\/outlines\/drafts["']\)/)
  assert.match(source, /@course_outline_router\.post\(["']\/course\/\{course_id\}\/patch-proposals\/\{proposal_id\}\/decide["']\)/)
  assert.match(source, /"course\.structure\.edit"/)
  assert.match(source, /"course\.script\.edit"/)
  assert.match(source, /"course\.publish"/)
  assert.match(source, /_require_draft_outline/)
  assert.match(source, /_require_draft_script/)
})

test('course release gate freezes one corpus lineage with an aligned draft outline and script', () => {
  const source = read('backend/app/services/course_build_service.py')
  assert.match(source, /没有可冻结的课程材料快照/)
  assert.match(source, /freeze_release_retrieval_snapshot/)
  assert.match(source, /发布必须指定同一草稿版本的课程结构与讲稿/)
  assert.match(source, /outline\.corpus_snapshot_id != corpus\.corpus_snapshot_id/)
  assert.match(source, /release\.retrieval_snapshot_id = retrieval\.retrieval_snapshot_id/)
})

test('course builder agent uses the natural-language proposal and evidence APIs, never the DSL creation path', () => {
  const panel = read('frontend/src/app/pages/course/build/CourseBuildAgentPanel.vue')
  const editor = read('frontend/src/api/course_editor.js')
  const layout = read('frontend/src/app/pages/course/build/BuildLayout.vue')
  const structure = read('frontend/src/app/pages/course/build/BuildStructurePage.vue')
  const scripts = read('frontend/src/app/pages/course/build/BuildScriptsPage.vue')
  assert.match(panel, /向助教智能体说明你想调整什么/)
  assert.match(panel, /runPrepAgentCommand/)
  assert.match(panel, /needs_clarification/)
  assert.match(panel, /getPrepAgentNodeEvidence/)
  assert.match(panel, /接受提案/)
  assert.doesNotMatch(panel, /outline:on_x:title/)
  assert.match(editor, /prep-agent\/commands/)
  assert.match(editor, /prep-agent\/batch-actions/)
  assert.match(editor, /\{ action \}/)
  assert.match(editor, /prep-agent\/evidence/)
  assert.match(layout, /batchRun/)
  assert.match(layout, /agentMessages/)
  assert.match(panel, /batchRunning/)
  assert.match(panel, /批量优化进行中/)
  assert.match(layout, /requestOrganize/)
  assert.match(layout, /:disabled="Boolean\(batchRun\)"/)
  assert.match(structure, /正在整理全部未锁定的课程节点/)
  assert.match(structure, /optimize_node_title/)
  assert.match(scripts, /正在统一优化全部未锁定讲稿的讲解节奏/)
  assert.match(scripts, /optimize_node_script/)
  assert.match(scripts, /optimize_all_scripts/)
  assert.match(scripts, /workbench\.selectedNode = item\.outline_node \|\| null/)
  assert.match(scripts, /workbench\.selectedNode = selected\.value\?\.outline_node \|\| null/)
  assert.match(structure, /reportOrganizeUnavailable/)
  assert.match(scripts, /reportOrganizeUnavailable/)
  assert.doesNotMatch(panel, /course-build-agent-batch-completed/)
})

test('PPT mapping client requires the multi-deck mapping contract', () => {
  const editor = read('frontend/src/api/course_editor.js')
  const backend = read('backend/app/api/v1/endpoints/course_build_editor.py')
  const mapping = read('frontend/src/app/pages/course/build/BuildMappingPage.vue')
  assert.match(editor, /ppt-mapping/)
  assert.match(backend, /"mapping_contract_version": "ppt-mapping\/v2"/)
  assert.match(backend, /"ppt_materials": ppt_materials/)
  assert.match(mapping, /mappingContractReady/)
  assert.match(mapping, /material_version_id/)
  assert.match(mapping, /ppt_materials/)
  assert.match(editor, /getPptMappingWorkspace/)
  assert.match(editor, /savePptMappings/)
  assert.match(editor, /matchPptMapping/)
  assert.match(backend, /ppt-mapping\/workspace/)
  assert.match(backend, /ppt-mapping\/match/)
  assert.match(backend, /save_ppt_mappings/)
  assert.match(mapping, /未找到可信候选页，可直接在页图中选择/)
  assert.match(mapping, /保存映射/)
})

test('media creation center uses the P4 batch plan, guarded confirmation, draft preview and playlist contracts', () => {
  const media = read('frontend/src/api/media_release.js')
  const page = read('frontend/src/app/pages/course/build/BuildMediaPage.vue')
  const backend = read('backend/app/api/v1/endpoints/media_release.py')
  const batch = read('backend/app/services/media_batch_service.py')
  const release = read('backend/app/services/media_release_service.py')
  const editor = read('backend/app/api/v1/endpoints/course_build_editor.py')
  assert.match(media, /\/providers\/health/)
  assert.match(media, /batch\/plan/)
  assert.match(media, /batch\/confirm/)
  assert.match(media, /batch\/\$\{encodeURIComponent\(batchId\)\}/)
  assert.match(media, /items\/\$\{encodeURIComponent\(itemId\)\}\/preview/)
  assert.match(media, /preview-playback/)
  assert.match(media, /audio-playlist/)
  assert.match(page, /planMediaBatch/)
  assert.match(page, /confirmMediaBatch/)
  assert.match(page, /getMediaBatch/)
  assert.match(page, /previewMediaReleaseItem/)
  assert.match(page, /previewMediaReleaseItemPlayback/)
  assert.match(page, /withPreviewAccessToken/)
  assert.match(page, /withAccessToken/)
  assert.match(page, /audio_url: withPreviewAccessToken\(audioPreview\?\.audio_url\)/)
  assert.match(page, /freezeAudioPlaylist/)
  assert.match(page, /paidTtsConfirmed/)
  assert.match(page, /script_node_db_id/)
  assert.match(backend, /@media_release_router\.post\("\/course\/\{course_id\}\/batch\/plan"\)/)
  assert.match(backend, /@media_release_router\.post\("\/course\/\{course_id\}\/batch\/confirm"\)/)
  assert.match(backend, /@media_release_router\.get\("\/course\/\{course_id\}\/batch\/\{batch_id\}"\)/)
  assert.match(backend, /items\/\{item_id\}\/preview/)
  assert.match(backend, /preview-playback/)
  assert.match(backend, /audio-playlist/)
  assert.match(backend, /"course\.media\.generate"/)
  assert.match(batch, /max_nodes/)
  assert.match(batch, /cache_hit_count/)
  assert.match(batch, /PPT 映射缺失/)
  assert.match(batch, /audio-playlist\/v1/)
  assert.match(release, /AUDIO_PLAYLIST_REQUIRED/)
  assert.match(release, /playlist_content_hash/)
  assert.match(backend, /has_formal_scripts/)
  assert.match(editor, /"script_node_db_id": node\.id/)
})
