[project]
name = "ai-course-system"
version = "0.1.0"
description = """本项目使用uv作为包管理器; 兼容Windows, Linux; Python版本: 3.12;
目前优先确保使用cpu运行文档处理模型."""
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "fastapi>=0.135.1",
    "langgraph>=0.6,<0.7",
    "pytest>=9.0.2",
    "sqlmodel>=0.0.37",
    "passlib[bcrypt]>=1.7.4",
    "bcrypt>=4.0.0",
    "pillow>=12.1.1",
    "pydantic-settings>=2.13.1",
    "python-dotenv>=1.2.2",
    "python-jose[cryptography]>=3.5.0",
    "python-multipart>=0.0.22",
    "uvicorn>=0.41.0",
    "httpx>=0.28.1",
    "docling>=2.81.0",
    "transformers>=4.57.6",
    "ruff>=0.15.7",
    "ty>=0.0.25",
    "onnxruntime>=1.24.4",
    "pymupdf>=1.27.2.3",
    "pdfplumber>=0.11.0",
    "python-docx>=1.1.0",
    "python-pptx>=1.0.0",
]
