#!/usr/bin/env sh
set -eu

: "${POSTGRES_CONTAINER_NAME:=smartcarb-postgres}"
: "${POSTGRES_DB:=ai_course}"
: "${AI_COURSE_APP_DB_USER:?AI_COURSE_APP_DB_USER is required}"
: "${AI_COURSE_MIGRATION_DB_USER:?AI_COURSE_MIGRATION_DB_USER is required}"

docker exec -i \
  -e APP_DB_USER="$AI_COURSE_APP_DB_USER" \
  -e APP_DB_OWNER="$AI_COURSE_MIGRATION_DB_USER" \
  "$POSTGRES_CONTAINER_NAME" sh -ceu '
  PGPASSWORD="$POSTGRES_PASSWORD" psql -v ON_ERROR_STOP=1 -U "$POSTGRES_USER" -d "$POSTGRES_DB" -v app_user="$APP_DB_USER" -v app_owner="$APP_DB_OWNER"
' <<'SQL'
GRANT USAGE ON SCHEMA public TO :"app_user";
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO :"app_user";
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO :"app_user";
ALTER DEFAULT PRIVILEGES FOR ROLE :"app_owner" IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO :"app_user";
ALTER DEFAULT PRIVILEGES FOR ROLE :"app_owner" IN SCHEMA public
  GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO :"app_user";
SQL
