"""学科知识库构建服务（DK1 起，CR1–CR3 扩展）。

确定性能力（导入/身份/分块/发布/检索）不调用生成模型、不访问网络；
embedding 推理走本地离线服务（CR2），查询经统一检索服务（CR3）。
"""

from app.services.discipline_knowledge.adjudication import adjudicate
from app.services.discipline_knowledge.builds import (
    PIPELINE_CORPUS,
    PIPELINE_LEGACY,
    CORPUS_STAGES,
    STAGE_DEPENDENCIES,
    DisciplineBuildError,
    apply_settle_counters,
    cancel_build,
    config_hash_for,
    corpus_disk_estimate_bytes,
    create_build,
    create_corpus_build,
    embedded_chunks,
    get_build,
    plan_corpus_shards,
    plan_delta,
    reserve_budget,
    retry_build,
    settle_budget,
    start_build,
    validate_build_scope,
)
from app.services.discipline_knowledge.corpus_index import (
    CORPUS_SCOPE,
    FTS_SCHEMA_VERSION,
    CorpusIndexError,
    activate_index,
    build_fts,
    close_fts_connections,
    create_release,
    fts_object_key_for,
    get_chunk_reference,
    get_release,
    get_release_manifest,
    open_fts_readonly,
    read_head,
    resolve_fts_root,
    validate_index,
)
from app.services.discipline_knowledge.corpus_search import (
    CorpusSearchService,
    reset_vector_cooldown,
)
from app.services.discipline_knowledge.corpus_source import (
    family_for,
    iter_source_records,
    resolve_source_root,
)
from app.services.discipline_knowledge.corpus_text import (
    CORPUS_CHUNKER_BASE,
    CORPUS_NORMALIZER_VERSION,
    CharFallbackTokenizer,
    CorpusTextError,
    chunk_document,
    get_store,
    metadata_hash_for,
    normalize_corpus_text,
    object_key_for,
    put_normalized_text,
    read_chunk_text,
    resolve_store_root,
)
from app.services.discipline_knowledge.decisions import (
    DisciplineDecisionError,
    merge_concepts,
    record_decision,
    revert_decision,
)
from app.services.discipline_knowledge.ingest import (
    DisciplineIngestError,
    import_legacy_seed,
    ingest_document,
    preview_document,
)
from app.services.discipline_knowledge.resolution import resolve_identity
from app.services.discipline_knowledge.validation import verify_assertion
from app.services.discipline_knowledge.work_items import (
    CORPUS_DEFERRED_STAGES,
    DEFERRED_STAGES,
    RETRYABLE_EMBED_ERRORS,
    DisciplineWorkError,
    claim_item,
    complete_item,
    fail_item,
    fingerprint_for,
    renew_lease,
    reap_expired_leases,
    run_corpus_batch,
    run_item,
)

__all__ = [
    "CORPUS_CHUNKER_BASE",
    "CORPUS_DEFERRED_STAGES",
    "CORPUS_NORMALIZER_VERSION",
    "CORPUS_STAGES",
    "DEFERRED_STAGES",
    "PIPELINE_CORPUS",
    "PIPELINE_LEGACY",
    "RETRYABLE_EMBED_ERRORS",
    "STAGE_DEPENDENCIES",
    "CharFallbackTokenizer",
    "CorpusIndexError",
    "CorpusSearchService",
    "CorpusTextError",
    "DisciplineBuildError",
    "DisciplineDecisionError",
    "DisciplineIngestError",
    "DisciplineWorkError",
    "adjudicate",
    "activate_index",
    "apply_settle_counters",
    "build_fts",
    "cancel_build",
    "chunk_document",
    "claim_item",
    "close_fts_connections",
    "complete_item",
    "config_hash_for",
    "corpus_disk_estimate_bytes",
    "create_build",
    "create_corpus_build",
    "create_release",
    "embedded_chunks",
    "fail_item",
    "family_for",
    "fingerprint_for",
    "fts_object_key_for",
    "get_build",
    "get_chunk_reference",
    "get_release",
    "get_release_manifest",
    "get_store",
    "import_legacy_seed",
    "ingest_document",
    "iter_source_records",
    "merge_concepts",
    "metadata_hash_for",
    "normalize_corpus_text",
    "object_key_for",
    "open_fts_readonly",
    "plan_corpus_shards",
    "plan_delta",
    "preview_document",
    "put_normalized_text",
    "read_chunk_text",
    "read_head",
    "record_decision",
    "renew_lease",
    "reap_expired_leases",
    "reserve_budget",
    "reset_vector_cooldown",
    "resolve_fts_root",
    "resolve_identity",
    "resolve_source_root",
    "resolve_store_root",
    "retry_build",
    "revert_decision",
    "run_corpus_batch",
    "run_item",
    "settle_budget",
    "start_build",
    "validate_build_scope",
    "validate_index",
    "verify_assertion",
]
