"""mapping_status_pending_review

Revision ID: 0006
Revises: 0005
Create Date: 2026-07-27 11:00:00

P1-4: Add PENDING_REVIEW to the question_source_mappings.status enum.

New candidate mappings generated by EduAgent+OCR now default to
``pending_review`` instead of ``auto_accepted``, so teacher review is
required before a candidate can be published. ``auto_accepted`` remains
valid for historical rows and for teacher-explicit approvals.

Dialect handling:
- PostgreSQL: ``ALTER TYPE mappingstatus ADD VALUE IF NOT EXISTS 'PENDING_REVIEW'``
- SQLite: SQLAlchemy emits ``sa.Enum`` as VARCHAR with a CHECK constraint.
  CHECK constraints cannot be edited in-place; we recreate by replacing
  the column type with a plain VARCHAR to avoid constraint violations.
  Application-level validation via the ``MappingStatus`` enum continues
  to enforce the allowed value set.
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers
revision: str = "0006"
down_revision: Union[str, None] = "0005"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


TABLE_NAME = "question_source_mappings"
COLUMN_NAME = "status"
NEW_VALUE = "PENDING_REVIEW"


def _dialect_name(bind) -> str:
    return bind.dialect.name


def _column_exists(bind, table: str, column: str) -> bool:
    from sqlalchemy import inspect
    inspector = inspect(bind)
    if table not in inspector.get_table_names():
        return False
    cols = {c["name"] for c in inspector.get_columns(table)}
    return column in cols


def upgrade() -> None:
    bind = op.get_bind()
    if not _column_exists(bind, TABLE_NAME, COLUMN_NAME):
        # Table or column missing — nothing to upgrade.
        return

    dialect = _dialect_name(bind)
    if dialect == "postgresql":
        # Add the new enum value. Use a raw, autocommit-guarded statement
        # because PostgreSQL does not allow ADD VALUE inside a transaction.
        op.execute(
            f"ALTER TYPE mappingstatus ADD VALUE IF NOT EXISTS '{NEW_VALUE}'"
        )
        return

    if dialect == "sqlite":
        # SQLite stores SQLModel/SQLAlchemy ``Enum`` columns as VARCHAR
        # with a CHECK constraint. SQLite does not support ``ALTER COLUMN``
        # in place, so we use batch mode to recreate the table with the
        # column redefined as a plain VARCHAR. The application-level
        # ``MappingStatus`` enum remains the single source of truth.
        with op.batch_alter_table(TABLE_NAME) as batch_op:
            batch_op.alter_column(
                COLUMN_NAME,
                existing_type=sa.Enum(
                    "UNASSIGNED", "AUTO_ACCEPTED", "TEACHER_EDITED",
                    "REJECTED", "STALE", "LOCKED",
                    name="mappingstatus",
                ),
                type_=sa.String(length=50),
                existing_nullable=False,
            )
        return

    # Other dialects: attempt the standard alter_column with a USING clause.
    op.alter_column(
        TABLE_NAME,
        COLUMN_NAME,
        existing_type=sa.Enum(
            "UNASSIGNED", "AUTO_ACCEPTED", "TEACHER_EDITED",
            "REJECTED", "STALE", "LOCKED",
            name="mappingstatus",
        ),
        type_=sa.String(length=50),
        existing_nullable=False,
        existing_server_default=None,
        postgresql_using=f"{COLUMN_NAME}::text",
    )


def downgrade() -> None:
    bind = op.get_bind()
    if not _column_exists(bind, TABLE_NAME, COLUMN_NAME):
        return

    dialect = _dialect_name(bind)

    # Move any rows that use PENDING_REVIEW back to AUTO_ACCEPTED so the
    # downgrade does not violate the original enum constraint.
    op.execute(
        f"UPDATE {TABLE_NAME} SET {COLUMN_NAME} = 'AUTO_ACCEPTED' "
        f"WHERE {COLUMN_NAME} = '{NEW_VALUE}'"
    )

    if dialect == "postgresql":
        # PostgreSQL enums cannot have values removed; leave the value in
        # place. Downgrade only normalizes the data above.
        return

    if dialect == "sqlite":
        # Restore the original Enum-typed column via batch mode.
        with op.batch_alter_table(TABLE_NAME) as batch_op:
            batch_op.alter_column(
                COLUMN_NAME,
                existing_type=sa.String(length=50),
                type_=sa.Enum(
                    "UNASSIGNED", "AUTO_ACCEPTED", "TEACHER_EDITED",
                    "REJECTED", "STALE", "LOCKED",
                    name="mappingstatus",
                ),
                existing_nullable=False,
            )
        return

    # Other dialects: standard alter_column.
    op.alter_column(
        TABLE_NAME,
        COLUMN_NAME,
        existing_type=sa.String(length=50),
        type_=sa.Enum(
            "UNASSIGNED", "AUTO_ACCEPTED", "TEACHER_EDITED",
            "REJECTED", "STALE", "LOCKED",
            name="mappingstatus",
        ),
        existing_nullable=False,
        existing_server_default=None,
    )
